id: P01EAA338
initial_creation_type: ocr
source_metadata:
  volumes:
    28dbe2149d5e4f3c8d832fc9f1b9bfe1:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: རྟེན་འབྲེལ་སྙིང་པོའི་སྔགས་ཐེམ་ཞིབ་མོར་བཀོད་པ།
      total_pages: 1464
      volume_number: 47
